apiVersion: cluster.ipfs.io/v1alpha1
kind: Ipfs
metadata:
  name: ipfs-sample-0
spec:
  url: apps.jephilli-4-11-04-28-0655.devcluster.openshift.com 
  ipfsStorage: 20Gi
  clusterStorage: 20Gi
  public: true
  replicas: 3
