# permissions for end users to edit circuitrelays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: circuitrelay-editor-role
rules:
- apiGroups:
  - cluster.ipfs.io
  resources:
  - circuitrelays
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ipfs.io
  resources:
  - circuitrelays/status
  verbs:
  - get
