# permissions for end users to view circuitrelays.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: circuitrelay-viewer-role
rules:
- apiGroups:
  - cluster.ipfs.io
  resources:
  - circuitrelays
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.ipfs.io
  resources:
  - circuitrelays/status
  verbs:
  - get
