# permissions for end users to edit ipfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipfs-editor-role
rules:
- apiGroups:
  - cluster.ipfs.io
  resources:
  - ipfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.ipfs.io
  resources:
  - ipfs/status
  verbs:
  - get
