# permissions for end users to view ipfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipfs-viewer-role
rules:
- apiGroups:
  - cluster.ipfs.io
  resources:
  - ipfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.ipfs.io
  resources:
  - ipfs/status
  verbs:
  - get
