---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.ipfs.io
  resources:
  - ipfs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.ipfs.io
  resources:
  - ipfs/finalizers
  verbs:
  - update
- apiGroups:
  - cache.ipfs.io
  resources:
  - ipfs/status
  verbs:
  - get
  - patch
  - update
