
---
apiVersion: cluster.ipfs.io/v1alpha1
kind: Ipfs
metadata:
  name: ipfs-sample-collab
spec:
  ipfsStorage: 2Gi
  clusterStorage: 1Gi
  replicas: 1
  networking:
    circuitRelays: 1
  follows:
  - name: gutenberg_es
    template: gutenberg-es.collab.ipfscluster.io 