---
apiVersion: cluster.ipfs.io/v1alpha1
kind: IpfsCluster
metadata:
  name: ipfs-sample
spec:
  ipfsStorage: 50Gi
  clusterStorage: 5Gi
  replicas: 2
  follows: []
  networking:
    circuitRelays: 2
